server:
  port: 8085
spring:
  rabbitmq:
    virtual-host: b2c
    host: 192.168.68.129
    username: b2c
    password: 123456
  application:
    name: goods-page
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}
b2c:
  thymeleaf:
    destPath: F:\xz\static-html\item